export const siteConfig = {
    name: "FaangPrepTracker - Leetcode Company-Wise Problems",
    description: "Practice FAANG interview coding problems. Track and solve company-specific technical interview questions from top tech companies like Amazon, Google, Facebook, Apple, Microsoft, and more.",
    url: "https://faangpreptracker.vercel.app",
    keywords: [
        "FAANG interview preparation",
        "coding interview questions",
        "technical interview practice",
        "leetcode problems",
        "Amazon interview questions",
        "Google interview preparation",
        "Facebook coding problems",
        "Apple interview questions",
        "Microsoft interview preparation",
        "company-wise coding problems",
        "coding interview tracker",
        "interview preparation",
        "data structures",
        "algorithms",
        "software engineering interviews",
        "product-based companies",
        "product-based companies interview questions",
        "product-based companies interview preparation",
        "product-based companies coding problems",
        "product-based companies technical interview questions",
        "product-based companies technical interview preparation",
        "leetcode company-wise problems",
        "leetcode company-wise problems preparation",
        "leetcode company-wise problems practice",
        "leetcode company-wise problems tracker",
    ]
}; 